import { hashPassword } from "./password";
import type {
  CalendarEvent,
  Comment,
  Community,
  Course,
  Database,
  Message,
  Notification,
  Post,
  Project,
  Review,
  Sale,
  User,
  VideoResource,
} from "./types";

export const COURSE_CATALOG_IDS = [
  "course-getting-started",
  "course-business-clarity",
  "course-learn-to-build-apps",
  "course-the-daily-pulse",
  "course-n8n-templates",
  "course-make-com-templates",
] as const;

export const OLD_COURSE_IDS = [
  "course-eem-1",
  "course-eem-2",
  "course-eem-3",
  "course-eem-4",
  "course-eem-5",
  "course-seo",
  "course-ai-seo",
  "course-ai",
  "course-n8n",
  "course-meta-ads",
  "course-leads",
  "course-start",
  "course-method",
  "course-models",
  "course-toolkit",
  "course-calls",
  "course-bonus",
];

export function createClassroomCourses(): Course[] {
  return [
    {
      id: "course-getting-started",
      slug: "getting-started-onboarding",
      title: "Getting Started (Onboarding)",
      description: "Learn exactly how to maximize this community, learn AI and make money.",
      accent: "from-[#6b6113] via-[#7d7316] to-[#4d460d]",
      badge: "FREE",
      unlockLevel: 1,
      price: 0,
      bannerBrand: "PSS COMMUNITY",
      bannerSubtitle: "START HERE",
      bannerTitle: "GETTING STARTED",
      watermark: "> start here_",
      glowColor: "yellow",
      isPremiumOnly: false,
      lessons: [
        {
          id: "l-gs-1-1",
          module: "Module 1: Onboarding & Community",
          title: "1.1 Welcome and Community Overview",
          videoTitle: "1.1 Welcome and Community Overview",
          duration: "4:12",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Welcome to Permanent Skills Academy!\n\nThis onboarding module gives you the foundational roadmap to navigate our community, access high-value frameworks, and leverage AI to build compounding digital assets.\n\nKey Recommendations:\n• Introduce yourself in the Community chat.\n• Complete each lesson in sequence.\n• Implement the worksheets and swipe files attached below each video.\n• Attend our live interactive workshops in the Meet tab.",
        },
        {
          id: "l-gs-1-2",
          module: "Module 1: Onboarding & Community",
          title: "1.2 Maximizing AI & Monetization Playbooks",
          videoTitle: "1.2 Maximizing AI & Monetization Playbooks",
          duration: "6:45",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Understand the core monetization mechanics: AI-driven client acquisition, building software tools, automated email retainers, and topical authority SEO.",
        },
        {
          id: "l-gs-1-3",
          module: "Module 1: Onboarding & Community",
          title: "1.3 Setting Up Your Environment & Toolchain",
          videoTitle: "1.3 Setting Up Your Environment & Toolchain",
          duration: "5:30",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Walkthrough of our recommended developer, automation, and AI stack to start shipping deliverables quickly.",
        },
      ],
    },
    {
      id: "course-business-clarity",
      slug: "business-clarity-course",
      title: "Business Clarity Course",
      description: "A simple step-by-step process to sell AI products and services.",
      accent: "from-[#0a0a0c] via-[#0d1612] to-[#08120c]",
      badge: "LEVEL 7",
      unlockLevel: 7,
      price: 99,
      bannerBrand: "PSS BUSINESS",
      bannerSubtitle: "UNLOCK AT LEVEL 7",
      bannerTitle: "BUSINESS CLARITY",
      watermark: "> make money_",
      glowColor: "green",
      isPremiumOnly: false,
      lessons: [
        {
          id: "l-bc-1-1",
          module: "Module 1: Offer Strategy",
          title: "1.1 Niche Selection & High-Ticket AI Offers",
          videoTitle: "1.1 Niche Selection & High-Ticket AI Offers",
          duration: "7:15",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Identifying lucrative client bottlenecks that modern AI solutions solve in hours, offer structuring, and value-based pricing.",
        },
        {
          id: "l-bc-1-2",
          module: "Module 1: Offer Strategy",
          title: "1.2 Client Acquisition & Outreach Funnels",
          videoTitle: "1.2 Client Acquisition & Outreach Funnels",
          duration: "8:40",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Cold email blueprints, automated LinkedIn outreach, and personalized video audit scripts that book high-intent discovery calls.",
        },
        {
          id: "l-bc-1-3",
          module: "Module 1: Offer Strategy",
          title: "1.3 Proposal Structuring & Closing Retainers",
          videoTitle: "1.3 Proposal Structuring & Closing Retainers",
          duration: "9:20",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "How to present deliverables, handle pricing objections, and secure long-term recurring retainers.",
        },
      ],
    },
    {
      id: "course-learn-to-build-apps",
      slug: "learn-to-build-apps",
      title: "Learn to Build Apps",
      description: "Learn the fundamentals of coding, building apps, and cloud deployments.",
      accent: "from-[#0a0a0c] via-[#0b1420] to-[#071018]",
      badge: "LEVEL 8",
      unlockLevel: 8,
      price: 149,
      bannerBrand: "PSS DEV",
      bannerSubtitle: "UNLOCK AT LEVEL 8",
      bannerTitle: "LEARN TO BUILD APPS",
      watermark: "> build apps_",
      glowColor: "blue",
      isPremiumOnly: false,
      lessons: [
        {
          id: "l-ba-1-1",
          module: "Module 1: Full-Stack Architecture",
          title: "1.1 Modern Web Architecture & Next.js Setup",
          videoTitle: "1.1 Modern Web Architecture & Next.js Setup",
          duration: "10:15",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Setting up a scalable Next.js App Router codebase, TypeScript strictness, and reactive UI component patterns.",
        },
        {
          id: "l-ba-1-2",
          module: "Module 1: Full-Stack Architecture",
          title: "1.2 Database Modeling & Server Actions",
          videoTitle: "1.2 Database Modeling & Server Actions",
          duration: "12:00",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "PostgreSQL schemas, ORM data relationships, secure API routes, and optimistic UI updates.",
        },
        {
          id: "l-ba-1-3",
          module: "Module 1: Full-Stack Architecture",
          title: "1.3 Cloud Deployments, Auth & CI/CD",
          videoTitle: "1.3 Cloud Deployments, Auth & CI/CD",
          duration: "14:20",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Continuous integration pipelines, production environment configurations, Vercel deployments, and custom domain SSL setups.",
        },
      ],
    },
    {
      id: "course-the-daily-pulse",
      slug: "the-daily-pulse",
      title: "The Daily Pulse 🔥",
      description: "Daily live sessions neatly cut up and organized so everything is easy to find.",
      accent: "from-[#0a0a0c] via-[#1a1008] to-[#120a05]",
      badge: "VIP",
      unlockLevel: 99,
      price: 199,
      bannerBrand: "PSS LIVE",
      bannerSubtitle: "DAILY SESSIONS",
      bannerTitle: "THE DAILY PULSE",
      watermark: "> daily pulse_",
      glowColor: "orange",
      isPremiumOnly: true,
      lessons: [
        {
          id: "l-dp-1-1",
          module: "Module 1: Live Breakdowns",
          title: "1.1 High-Converting Store Teardowns & Live Audits",
          videoTitle: "1.1 High-Converting Store Teardowns & Live Audits",
          duration: "15:30",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Live audit of member funnels, conversion optimization suggestions, and real-time copy refactoring.",
        },
        {
          id: "l-dp-1-2",
          module: "Module 1: Live Breakdowns",
          title: "1.2 Algorithm Shifts & Traffic Arbitrage",
          videoTitle: "1.2 Algorithm Shifts & Traffic Arbitrage",
          duration: "18:45",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Deep dive into recent organic search changes, social algorithm updates, and paid acquisition testing strategies.",
        },
        {
          id: "l-dp-1-3",
          module: "Module 1: Live Breakdowns",
          title: "1.3 Weekly Deep Dive: Live Q&A and Build Session",
          videoTitle: "1.3 Weekly Deep Dive: Live Q&A and Build Session",
          duration: "22:10",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Interactive live session building custom workflows and answering member technical questions live.",
        },
      ],
    },
    {
      id: "course-n8n-templates",
      slug: "n8n-course-templates",
      title: "n8n Course + Templates",
      description: "Step-by-step n8n automation course + amazing n8n templates ready for use.",
      accent: "from-[#0a0a0c] via-[#1a0b12] to-[#12070c]",
      badge: "LEVEL 6",
      unlockLevel: 6,
      price: 89,
      bannerBrand: "PSS AUTOMATE",
      bannerSubtitle: "UNLOCK AT LEVEL 6",
      bannerTitle: "N8N AUTOMATION",
      watermark: "> n8n_",
      glowColor: "red",
      isPremiumOnly: false,
      lessons: [
        {
          id: "l-n8n-1-1",
          module: "Module 1: n8n Foundations & Workflows",
          title: "1.1 n8n Setup & Webhook Engine Architecture",
          videoTitle: "1.1 n8n Setup & Webhook Engine Architecture",
          duration: "8:25",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Setting up your self-hosted n8n instance, configuring inbound webhook triggers, and error management.",
        },
        {
          id: "l-n8n-1-2",
          module: "Module 1: n8n Foundations & Workflows",
          title: "1.2 AI Lead Enrichment & Extraction Pipelines",
          videoTitle: "1.2 AI Lead Enrichment & Extraction Pipelines",
          duration: "11:15",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Building multi-agent nodes with OpenAI / Claude for automated research, web scraping, and spreadsheet population.",
        },
        {
          id: "l-n8n-1-3",
          module: "Module 1: n8n Foundations & Workflows",
          title: "1.3 Production n8n Templates Download & Setup",
          videoTitle: "1.3 Production n8n Templates Download & Setup",
          duration: "13:40",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Importing our pre-built automation workflows for CRM syncing, automated notifications, and AI email triage.",
        },
      ],
    },
    {
      id: "course-make-com-templates",
      slug: "make-com-course-templates",
      title: "Make.com Course + Templates",
      description: "Step-by-step Make + Airtable automation course + templates that are ready for use.",
      accent: "from-[#0a0a0c] via-[#140b1e] to-[#0c0614]",
      badge: "VIP",
      unlockLevel: 99,
      price: 129,
      bannerBrand: "PSS INTEGRATE",
      bannerSubtitle: "VIP ONLY",
      bannerTitle: "MAKE.COM + AIRTABLE",
      watermark: "> make.com_",
      glowColor: "purple",
      isPremiumOnly: true,
      lessons: [
        {
          id: "l-make-1-1",
          module: "Module 1: Make & Airtable Mastery",
          title: "1.1 Make.com Core Architecture & Router Mastery",
          videoTitle: "1.1 Make.com Core Architecture & Router Mastery",
          duration: "9:10",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Mastering complex data bundles, array aggregators, error handlers, and filter directives.",
        },
        {
          id: "l-make-1-2",
          module: "Module 1: Make & Airtable Mastery",
          title: "1.2 Airtable Relational Database Schemas",
          videoTitle: "1.2 Airtable Relational Database Schemas",
          duration: "12:35",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Designing clean multi-table relational architectures with linked records, rollup metrics, and automated view triggers.",
        },
        {
          id: "l-make-1-3",
          module: "Module 1: Make & Airtable Mastery",
          title: "1.3 Ready-to-Use Production Templates & Clones",
          videoTitle: "1.3 Ready-to-Use Production Templates & Clones",
          duration: "16:00",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Step-by-step cloning guide for our top 5 revenue-generating scenarios: E-commerce inventory sync, CRM enrichment, and content distribution.",
        },
      ],
    },
  ];
}

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 3600 * 1000).toISOString();
}

function daysAgo(days: number) {
  return hoursAgo(days * 24);
}

function atDate(year: number, month: number, day: number, hour = 21, minute = 0) {
  return new Date(year, month - 1, day, hour, minute, 0).toISOString();
}

export function createSeed(): Database {
  const adminHash = hashPassword("admin@permanentseo.com");
  const memberHash = hashPassword("member123");

  const users: User[] = [
    {
      id: "u-admin",
      email: "admin@permanentseo.com",
      passwordHash: adminHash,
      name: "Permanent Skills Admin",
      username: "pss-admin",
      bio: "Founder of Permanent Skills Academy. Helping builders, founders, and students master high-value digital systems.",
      role: "admin",
      status: "approved",
      points: 540,
      points7d: 22,
      points30d: 86,
      avatarColor: "#18181b",
      location: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      joinedAt: "2025-01-12T08:00:00.000Z",
      lastSeenAt: new Date().toISOString(),
      loginCount: 186,
      isPremium: true,
      language: "English",
      ipAddress: "192.168.1.1",
      affiliateCode: "VEX-ADMIN",
      affiliateClicks: 128,
      affiliateSignups: 14,
      affiliateEarnings: 126,
    },
    {
      id: "u-manager",
      email: "manager@permanentseo.com",
      passwordHash: memberHash,
      name: "Sarah Jenkins",
      username: "sarah-manager",
      bio: "Community & Student Success Specialist.",
      role: "member",
      status: "approved",
      points: 340,
      points7d: 28,
      points30d: 140,
      avatarColor: "#5051F9",
      location: "New York, USA",
      lat: 40.7128,
      lng: -74.006,
      joinedAt: "2025-06-15T09:00:00.000Z",
      lastSeenAt: hoursAgo(0.1),
      loginCount: 92,
      isPremium: true,
      language: "English",
      ipAddress: "198.51.100.22",
      affiliateCode: "VEX-SARAH",
      affiliateClicks: 45,
      affiliateSignups: 8,
      affiliateEarnings: 72,
    },
    {
      id: "u-daniel",
      email: "daniel@example.com",
      passwordHash: memberHash,
      name: "Daniel Jason",
      username: "daniel-jason",
      bio: "Building and scaling D2C e-commerce stores.",
      role: "member",
      status: "approved",
      points: 140,
      points7d: 16,
      points30d: 95,
      avatarColor: "#d97706",
      location: "Sydney, Australia",
      lat: -33.8688,
      lng: 151.2093,
      joinedAt: "2026-02-14T11:00:00.000Z",
      lastSeenAt: hoursAgo(1.5),
      loginCount: 52,
      isPremium: true,
      language: "English",
      ipAddress: "139.130.4.5",
      affiliateCode: "VEX-DANIEL",
      affiliateClicks: 18,
      affiliateSignups: 2,
      affiliateEarnings: 18,
    },
    {
      id: "u-ayaan",
      email: "ayaan@example.com",
      passwordHash: memberHash,
      name: "Ayaan Malik",
      username: "ayaan-malik",
      bio: "Operations specialist and retention consultant helping brands scale.",
      role: "member",
      status: "approved",
      points: 168,
      points7d: 19,
      points30d: 114,
      avatarColor: "#0ea5e9",
      location: "Karachi, Pakistan",
      lat: 24.8607,
      lng: 67.0011,
      joinedAt: "2026-03-04T10:00:00.000Z",
      lastSeenAt: hoursAgo(0.2),
      loginCount: 64,
      isPremium: true,
      language: "English",
      ipAddress: "182.185.120.45",
      affiliateCode: "PSS-AYAAN",
      affiliateClicks: 22,
      affiliateSignups: 3,
      affiliateEarnings: 27,
    },
    {
      id: "u-priya",
      email: "priya@example.com",
      passwordHash: memberHash,
      name: "Priya Sharma",
      username: "priya-sharma",
      bio: "Content strategist. I turn one idea into months of search-ready assets.",
      role: "member",
      status: "approved",
      points: 102,
      points7d: 12,
      points30d: 28,
      avatarColor: "#db2777",
      location: "Mumbai, India",
      lat: 19.076,
      lng: 72.8777,
      joinedAt: "2026-04-18T09:00:00.000Z",
      lastSeenAt: hoursAgo(1),
      loginCount: 41,
      isPremium: true,
      language: "English",
      ipAddress: "103.212.144.18",
      affiliateCode: "PSS-PRIYA",
      affiliateClicks: 9,
      affiliateSignups: 1,
      affiliateEarnings: 9,
    },
    {
      id: "u-james",
      email: "james@example.com",
      passwordHash: memberHash,
      name: "James Carter",
      username: "james-carter",
      bio: "Agency owner. Building retainers around permanent skill systems, not one-off tactics.",
      role: "member",
      status: "approved",
      points: 122,
      points7d: 8,
      points30d: 23,
      avatarColor: "#16a34a",
      location: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      joinedAt: "2026-02-11T12:00:00.000Z",
      lastSeenAt: hoursAgo(4),
      loginCount: 73,
      isPremium: true,
      language: "English",
      ipAddress: "82.165.197.1",
      affiliateCode: "PSS-JAMES",
      affiliateClicks: 31,
      affiliateSignups: 4,
      affiliateEarnings: 36,
    },
    {
      id: "u-sofia",
      email: "sofia@example.com",
      passwordHash: memberHash,
      name: "Sofia Alvarez",
      username: "sofia-alvarez",
      bio: "Coach for consultants who want inbound that still works in 3 years.",
      role: "member",
      status: "approved",
      points: 98,
      points7d: 6,
      points30d: 21,
      avatarColor: "#7c3aed",
      location: "Austin, USA",
      lat: 30.2672,
      lng: -97.7431,
      joinedAt: "2026-05-02T15:00:00.000Z",
      lastSeenAt: hoursAgo(26),
      loginCount: 29,
      isPremium: false,
      language: "English",
      ipAddress: "104.28.19.102",
      affiliateCode: "PSS-SOFIA",
      affiliateClicks: 4,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-wei",
      email: "wei@example.com",
      passwordHash: memberHash,
      name: "Chen Wei",
      username: "chen-wei",
      bio: "Ecommerce operator applying authority SEO to product education hubs.",
      role: "member",
      status: "approved",
      points: 67,
      points7d: 7,
      points30d: 15,
      avatarColor: "#ea580c",
      location: "Singapore",
      lat: 1.3521,
      lng: 103.8198,
      joinedAt: "2026-06-20T08:00:00.000Z",
      lastSeenAt: hoursAgo(3),
      loginCount: 18,
      isPremium: true,
      language: "English",
      ipAddress: "118.189.201.33",
      affiliateCode: "PSS-WEI",
      affiliateClicks: 6,
      affiliateSignups: 1,
      affiliateEarnings: 9,
    },
    {
      id: "u-amira",
      email: "amira@example.com",
      passwordHash: memberHash,
      name: "Amira Hassan",
      username: "amira-hassan",
      bio: "Consultant helping service businesses become the obvious search answer.",
      role: "member",
      status: "approved",
      points: 63,
      points7d: 4,
      points30d: 13,
      avatarColor: "#0891b2",
      location: "Dubai, UAE",
      lat: 25.2769,
      lng: 55.2962,
      joinedAt: "2026-01-28T11:00:00.000Z",
      lastSeenAt: hoursAgo(8),
      loginCount: 52,
      isPremium: true,
      language: "English",
      ipAddress: "94.200.12.180",
      affiliateCode: "PSS-AMIRA",
      affiliateClicks: 11,
      affiliateSignups: 2,
      affiliateEarnings: 18,
    },
    {
      id: "u-noah",
      email: "noah@example.com",
      passwordHash: memberHash,
      name: "Noah Bennett",
      username: "noah-bennett",
      bio: "Freelance strategist. Here to replace random tactics with a repeatable system.",
      role: "member",
      status: "approved",
      points: 58,
      points7d: 4,
      points30d: 12,
      avatarColor: "#4f46e5",
      location: "Sydney, Australia",
      lat: -33.8688,
      lng: 151.2093,
      joinedAt: "2026-07-09T07:00:00.000Z",
      lastSeenAt: hoursAgo(12),
      loginCount: 21,
      isPremium: false,
      language: "English",
      ipAddress: "139.130.4.5",
      affiliateCode: "PSS-NOAH",
      affiliateClicks: 2,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-lisa",
      email: "lisa@example.com",
      passwordHash: memberHash,
      name: "Lisa Okonkwo",
      username: "lisa-okonkwo",
      bio: "Brand strategist pairing positioning with search intent.",
      role: "member",
      status: "approved",
      points: 44,
      points7d: 3,
      points30d: 8,
      avatarColor: "#be123c",
      location: "Lagos, Nigeria",
      lat: 6.5244,
      lng: 3.3792,
      joinedAt: "2026-08-01T13:00:00.000Z",
      lastSeenAt: hoursAgo(30),
      loginCount: 14,
      isPremium: false,
      language: "English",
      ipAddress: "102.89.23.11",
      affiliateCode: "PSS-LISA",
      affiliateClicks: 1,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-marco",
      email: "marco@example.com",
      passwordHash: memberHash,
      name: "Marco Rossi",
      username: "marco-rossi",
      bio: "Local SEO for multi-location service brands across Europe.",
      role: "member",
      status: "approved",
      points: 36,
      points7d: 2,
      points30d: 6,
      avatarColor: "#0f766e",
      location: "Milan, Italy",
      lat: 45.4642,
      lng: 9.19,
      joinedAt: "2026-08-14T16:00:00.000Z",
      lastSeenAt: hoursAgo(50),
      loginCount: 11,
      isPremium: false,
      language: "English",
      ipAddress: "151.48.90.14",
      affiliateCode: "PSS-MARCO",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-hana",
      email: "hana@example.com",
      passwordHash: memberHash,
      name: "Hana Kim",
      username: "hana-kim",
      bio: "Technical SEO and information architecture for growing publications.",
      role: "member",
      status: "approved",
      points: 12,
      points7d: 5,
      points30d: 12,
      avatarColor: "#9333ea",
      location: "Seoul, South Korea",
      lat: 37.5665,
      lng: 126.978,
      joinedAt: daysAgo(12),
      lastSeenAt: hoursAgo(6),
      loginCount: 7,
      isPremium: false,
      language: "English",
      ipAddress: "211.234.118.9",
      affiliateCode: "PSS-HANA",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-omar",
      email: "omar@example.com",
      passwordHash: memberHash,
      name: "Omar Farooq",
      username: "omar-farooq",
      bio: "Learning a durable skill stack for my consulting practice.",
      role: "member",
      status: "pending",
      points: 0,
      points7d: 0,
      points30d: 0,
      avatarColor: "#64748b",
      location: "Lahore, Pakistan",
      lat: 31.5204,
      lng: 74.3587,
      joinedAt: hoursAgo(6),
      lastSeenAt: hoursAgo(6),
      loginCount: 1,
      isPremium: false,
      language: "English",
      ipAddress: "39.40.18.22",
      affiliateCode: "PSS-OMAR",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
      application: {
        fullName: "Omar Farooq",
        phone: "+92 300 5550199",
        country: "Pakistan",
        city: "Lahore",
        profession: "Independent consultant",
        experience: "2-4 years",
        website: "https://omarfarooq.co",
        goals: "I want a repeatable SEO and skill system so my pipeline is not dependent on referrals.",
        howHeard: "A colleague in the community",
        notes: "Independent consultant with a few years of SEO work. Looking for a durable system.",
      },
    },
    {
      id: "u-alex",
      email: "alex.rivera@growthops.io",
      passwordHash: memberHash,
      name: "Alex Rivera",
      username: "alex-rivera",
      bio: "Performance marketer and growth engineer looking to build durable SEO and lifecycle compounding.",
      role: "member",
      status: "pending",
      points: 0,
      points7d: 0,
      points30d: 0,
      avatarColor: "#0284c7",
      location: "Austin, TX, USA",
      lat: 30.2672,
      lng: -97.7431,
      joinedAt: hoursAgo(3),
      lastSeenAt: hoursAgo(3),
      loginCount: 1,
      isPremium: true,
      language: "English",
      ipAddress: "172.56.21.88",
      affiliateCode: "PSS-ALEX",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
      application: {
        fullName: "Alex Rivera",
        phone: "+1 512 555 0144",
        country: "United States",
        city: "Austin",
        profession: "Head of Growth / Founder",
        experience: "5+ years",
        website: "https://growthops.io",
        goals: "Transition our agency from paid ad reliance to organic SEO asset compounding and high-retention email funnels.",
        howHeard: "Twitter / X thread",
        notes: "Experienced agency founder looking to implement permanent skill systems across portfolio brands.",
      },
    },
    {
      id: "u-elena",
      email: "elena.rostova@designsystems.de",
      passwordHash: memberHash,
      name: "Elena Rostova",
      username: "elena-rostova",
      bio: "UI/UX architect and frontend developer building scalable web products.",
      role: "member",
      status: "pending",
      points: 0,
      points7d: 0,
      points30d: 0,
      avatarColor: "#ec4899",
      location: "Berlin, Germany",
      lat: 52.52,
      lng: 13.405,
      joinedAt: hoursAgo(2),
      lastSeenAt: hoursAgo(2),
      loginCount: 1,
      isPremium: false,
      language: "English",
      ipAddress: "91.64.201.12",
      affiliateCode: "PSS-ELENA",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
      application: {
        fullName: "Elena Rostova",
        phone: "+49 30 5550188",
        country: "Germany",
        city: "Berlin",
        profession: "Senior Product Designer",
        experience: "4-6 years",
        website: "https://elenarostova.design",
        goals: "Master full-stack automation, high-converting offer design, and community engineering.",
        howHeard: "YouTube masterclass",
        notes: "Specializes in design systems. Wants to launch and scale her own digital academy.",
      },
    },
    {
      id: "u-tariq",
      email: "tariq@almansoor-media.ae",
      passwordHash: memberHash,
      name: "Tariq Al-Mansoor",
      username: "tariq-mansoor",
      bio: "Digital media operator and content systems director.",
      role: "member",
      status: "pending",
      points: 0,
      points7d: 0,
      points30d: 0,
      avatarColor: "#d97706",
      location: "Dubai, UAE",
      lat: 25.2048,
      lng: 55.2708,
      joinedAt: hoursAgo(1),
      lastSeenAt: hoursAgo(1),
      loginCount: 1,
      isPremium: true,
      language: "English",
      ipAddress: "94.200.15.4",
      affiliateCode: "PSS-TARIQ",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
      application: {
        fullName: "Tariq Al-Mansoor",
        phone: "+971 4 555 0192",
        country: "United Arab Emirates",
        city: "Dubai",
        profession: "Media Agency Director",
        experience: "3-5 years",
        website: "https://almansoor-media.ae",
        goals: "Build an enterprise-grade retention engine and train our 12-person team on permanent skill frameworks.",
        howHeard: "Referral from a mastermind member",
        notes: "Managing multi-channel media operations across MENA region.",
      },
    },
    {
      id: "u-lucas",
      email: "lucas.vance@vancestrategies.co.uk",
      passwordHash: memberHash,
      name: "Lucas Vance",
      username: "lucas-vance",
      bio: "B2B growth consultant optimizing retention and email deliverability pipelines.",
      role: "member",
      status: "pending",
      points: 0,
      points7d: 0,
      points30d: 0,
      avatarColor: "#0284c7",
      location: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      joinedAt: hoursAgo(0.7),
      lastSeenAt: hoursAgo(0.7),
      loginCount: 1,
      isPremium: true,
      language: "English",
      ipAddress: "86.14.92.110",
      affiliateCode: "PSS-LUCAS",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
      application: {
        fullName: "Lucas Vance",
        phone: "+44 20 7946 0912",
        country: "United Kingdom",
        city: "London",
        profession: "B2B Growth Consultant",
        experience: "5+ years",
        website: "https://vancestrategies.co.uk",
        goals: "Install permanent lifecycle automation frameworks across 8 ongoing enterprise client accounts.",
        howHeard: "Newsletter recommendation",
        notes: "High-value B2B operator looking for advanced systems and deliverability playbooks.",
      },
    },
    {
      id: "u-maya",
      email: "maya.lin@tokyomedia.jp",
      passwordHash: memberHash,
      name: "Maya Lin",
      username: "maya-lin",
      bio: "Content engineer and automation developer building programmatic SEO engines.",
      role: "member",
      status: "pending",
      points: 0,
      points7d: 0,
      points30d: 0,
      avatarColor: "#8b5cf6",
      location: "Tokyo, Japan",
      lat: 35.6762,
      lng: 139.6503,
      joinedAt: hoursAgo(0.5),
      lastSeenAt: hoursAgo(0.5),
      loginCount: 1,
      isPremium: false,
      language: "English",
      ipAddress: "133.242.18.90",
      affiliateCode: "PSS-MAYA",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
      application: {
        fullName: "Maya Lin",
        phone: "+81 3 5555 0143",
        country: "Japan",
        city: "Tokyo",
        profession: "Automation Developer",
        experience: "3-4 years",
        website: "https://mayalin.dev",
        goals: "Combine AI workflows with topical authority architectures to launch niche content hubs.",
        howHeard: "Twitter / X technical breakdown",
        notes: "Strong technical background, looking for monetization clarity and curriculum access.",
      },
    },
    {
      id: "u-carlos",
      email: "carlos@mendezgrowth.io",
      passwordHash: memberHash,
      name: "Carlos Mendez",
      username: "carlos-mendez",
      bio: "SaaS founder and lifecycle retention specialist.",
      role: "member",
      status: "pending",
      points: 0,
      points7d: 0,
      points30d: 0,
      avatarColor: "#10b981",
      location: "Mexico City, Mexico",
      lat: 19.4326,
      lng: -99.1332,
      joinedAt: hoursAgo(0.2),
      lastSeenAt: hoursAgo(0.2),
      loginCount: 1,
      isPremium: true,
      language: "English",
      ipAddress: "189.204.44.12",
      affiliateCode: "PSS-CARLOS",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
      application: {
        fullName: "Carlos Mendez",
        phone: "+52 55 1234 5678",
        country: "Mexico",
        city: "Mexico City",
        profession: "SaaS Founder",
        experience: "6+ years",
        website: "https://mendezgrowth.io",
        goals: "Replace churn-heavy paid traffic with evergreen organic authority and high-converting email sequences.",
        howHeard: "Podcast episode",
        notes: "Scaling a B2B SaaS tool with 4,000 active users.",
      },
    },
  ];

  const posts: Post[] = [
    {
      id: "p-ecom-welcome",
      authorId: "u-admin",
      category: "chat",
      title: "👋 Welcome to Permanent Skills Academy",
      body: "Welcome everyone! This community is designed to help you master durable skills, AI automations, systems architecture, and compounded digital growth. Make sure to introduce yourself below and check out the Classroom! 👇",
      pinned: true,
      communityId: "comm-students",
      likes: ["u-ayaan", "u-priya", "u-james", "u-sofia", "u-wei", "u-amira"],
      createdAt: "2026-07-03T10:00:00.000Z",
      thumbnail: "ecom-mail",
    },
    {
      id: "p-ecom-entrepreneur",
      authorId: "u-daniel",
      category: "chat",
      title: "💼 Entrepreneurship",
      body: "Being a business owner means believing before others believe. Keep building your vision until your execution speaks for itself. The retention frameworks and deliverability setups in the classroom are game changers!",
      pinned: false,
      communityId: "comm-students",
      likes: ["u-admin", "u-priya", "u-ayaan", "u-sofia"],
      createdAt: daysAgo(5),
    },
    {
      id: "p-team-welcome",
      authorId: "u-admin",
      category: "chat",
      title: "🔒 VEX Media Internal Team Protocols & Client Standards",
      body: "Team specialists: welcome to the internal workspace. As a team member, you have full access to watch training modules, review SOPs, leave comments and questions, and take notes. Let's deliver exceptional ROI for our client roster!",
      pinned: true,
      communityId: "comm-team",
      likes: ["u-manager", "u-priya"],
      createdAt: daysAgo(3),
    },
    {
      id: "p-replay",
      authorId: "u-admin",
      category: "recorded",
      title: "Replay: Skill vs. Shortcut?",
      body: "In this session we run community Q&A. We cover why durable skills beat rented traffic, how to pick one offer, and what to do when a tactic stops working. Watch the replay and drop questions below.",
      pinned: false,
      communityId: "comm-students",
      likes: ["u-ayaan", "u-priya", "u-james"],
      createdAt: hoursAgo(16),
      thumbnail: "replay",
    },
    {
      id: "p-win",
      authorId: "u-james",
      category: "wins",
      title: "First inbound clients from the method",
      body: "Launched the authority pages last month and was skeptical it would actually compound. Closed 3 inbound clients this week. Pipeline finally feels like an asset, not a gamble.",
      pinned: true,
      likes: ["u-admin", "u-ayaan", "u-sofia", "u-wei", "u-amira"],
      createdAt: daysAgo(13),
    },
    {
      id: "p-welcome",
      authorId: "u-admin",
      category: "chat",
      title: "Welcome 👋",
      body: "Welcome to Permanent Skill Strategy. So happy you are here. Whether you are brand new or already running offers, start with the Classroom path, introduce yourself below, and come to the next live call.",
      pinned: true,
      likes: ["u-priya", "u-noah", "u-hana"],
      createdAt: "2025-10-25T09:00:00.000Z",
    },
    {
      id: "p-chat-1",
      authorId: "u-priya",
      category: "chat",
      title: "How many pages before you promote?",
      body: "I have 8 supporting articles and 1 pillar. Is that enough to start internal linking in earnest, or should I wait until 15?",
      pinned: false,
      likes: ["u-ayaan", "u-hana"],
      createdAt: hoursAgo(20),
    },
    {
      id: "p-win-2",
      authorId: "u-sofia",
      category: "wins",
      title: "Booked my calendar from organic",
      body: "Two discovery calls this week came from a single case-study page I built using the Start Here module. Small win, but it feels different from chasing likes.",
      pinned: false,
      likes: ["u-james", "u-amira", "u-admin"],
      createdAt: daysAgo(2),
    },
    {
      id: "p-review",
      authorId: "u-ayaan",
      category: "reviews",
      title: "Clear system, not hype",
      body: "I have been through a lot of tactic-heavy trainings. This is the first one that treats skills like an asset. The live calls are practical and the classroom path is easy to follow.",
      pinned: false,
      likes: ["u-admin", "u-james"],
      createdAt: daysAgo(9),
    },
    {
      id: "p-recorded-2",
      authorId: "u-admin",
      category: "recorded",
      title: "Replay: Offer architecture workshop",
      body: "We mapped four business models onto the same skill system: coaching, productized service, education, and local. Recording is in Archived Calls.",
      pinned: false,
      likes: ["u-wei", "u-marco"],
      createdAt: daysAgo(6),
      thumbnail: "workshop",
    },
    {
      id: "p-chat-2",
      authorId: "u-hana",
      category: "chat",
      title: "Intro — technical SEO + publishing",
      body: "Hi everyone. I work on information architecture for publications. Excited to apply the Permanent Skill Method to topic clusters instead of one-off posts.",
      pinned: false,
      likes: ["u-priya"],
      createdAt: daysAgo(1),
    },
  ];

  const comments: Comment[] = [
    { id: "c-ecom-1", postId: "p-ecom-welcome", authorId: "u-daniel", body: "Glad to be here! Looking forward to implementing the retention systems.", createdAt: daysAgo(21), status: "approved" },
    { id: "c-ecom-2", postId: "p-ecom-welcome", authorId: "u-priya", body: "The deliverability framework is brilliant. Excited to be part of the community!", createdAt: daysAgo(20), status: "approved" },
    { id: "c-ecom-3", postId: "p-ecom-welcome", authorId: "u-james", body: "We warmed up our dedicated sending IP following Module 2 and saw inboxing jump to 98%.", createdAt: daysAgo(18), status: "approved" },
    { id: "c-ecom-4", postId: "p-ecom-welcome", authorId: "u-sofia", body: "Figma swipe files are top notch. Thank you for sharing these templates.", createdAt: daysAgo(15), status: "approved" },
    { id: "c-ecom-5", postId: "p-ecom-welcome", authorId: "u-wei", body: "Excited to connect with fellow e-commerce brand operators here.", createdAt: daysAgo(12), status: "approved" },
    { id: "c-ecom-6", postId: "p-ecom-welcome", authorId: "u-amira", body: "Welcome everyone! Make sure to set up DMARC records before scaling volume.", createdAt: daysAgo(10), status: "approved" },
    { id: "c-ecom-7", postId: "p-ecom-welcome", authorId: "u-ayaan", body: "If anyone has questions on setting up segmentation flows, feel free to drop them below.", createdAt: daysAgo(8), status: "approved" },
    { id: "c-ecom-8", postId: "p-ecom-welcome", authorId: "u-lisa", body: "Starting the Module 1 Introduction overview today!", createdAt: daysAgo(5), status: "approved" },
    { id: "c-ecom-9", postId: "p-ecom-welcome", authorId: "u-manager", body: "Welcome everyone! Feel free to ask questions anytime in the chat or reach out directly.", createdAt: daysAgo(2), status: "approved" },
    { id: "c1", postId: "p-replay", authorId: "u-ayaan", body: "The section on rented vs owned attention was excellent.", createdAt: hoursAgo(14), status: "approved" },
    { id: "c2", postId: "p-replay", authorId: "u-priya", body: "Can we get the offer worksheet from the call in Toolkit?", createdAt: hoursAgo(12), status: "approved" },
    { id: "c3", postId: "p-replay", authorId: "u-james", body: "Watching with my team tomorrow. Thank you.", createdAt: hoursAgo(10), status: "approved" },
    { id: "c4", postId: "p-win", authorId: "u-admin", body: "This is the compounding we talk about. Document the pages that converted.", createdAt: daysAgo(12), status: "approved" },
    { id: "c5", postId: "p-win", authorId: "u-sofia", body: "Congrats James. Which cluster was the first client from?", createdAt: daysAgo(12), status: "approved" },
    { id: "c6", postId: "p-welcome", authorId: "u-noah", body: "Glad to be here. Starting the classroom tonight.", createdAt: daysAgo(20), status: "approved" },
    { id: "c7", postId: "p-chat-1", authorId: "u-admin", body: "Ship the 8, interlink tightly, then add. Waiting for a magic number usually delays learning.", createdAt: hoursAgo(18), status: "approved" },
    { id: "c8", postId: "p-win-2", authorId: "u-amira", body: "Love this. Case studies are underrated authority assets.", createdAt: daysAgo(1), status: "approved" },
    { id: "c-les-1", postId: "l-eem-1-1", authorId: "u-admin", body: "Welcome to Module 1! Make sure to grab the Figma swipe files linked above and review the course roadmap.", createdAt: hoursAgo(5), status: "approved" },
    { id: "c-les-2", postId: "l-eem-1-1", authorId: "u-ayaan", body: "The breakdown of why owned audience assets compound faster than paid ads was super clear.", createdAt: hoursAgo(3), status: "approved" },
    { id: "c-les-4", postId: "l-eem-1-1", authorId: "u-noah", body: "Can we apply these same segmentation principles to B2B eCommerce stores as well?", createdAt: hoursAgo(0.5), status: "pending" },
    { id: "c-pending-1", postId: "p-ecom-welcome", authorId: "u-daniel", body: "Could someone clarify if the cold outreach email templates from Module 1 are also compliant with EU GDPR regulations?", createdAt: hoursAgo(1.5), status: "pending" },
    { id: "c-pending-2", postId: "p-ecom-entrepreneur", authorId: "u-priya", body: "This mindset framework resonates heavily. When scaling to $50k/mo, how did you balance client delivery with building owned audience assets?", createdAt: hoursAgo(0.8), status: "pending" },
    { id: "c-pending-3", postId: "p-win", authorId: "u-sofia", body: "Massive milestone James! Did you use automated internal link scoring before publishing the cluster?", createdAt: hoursAgo(0.4), status: "pending" },
    { id: "c-pending-4", postId: "p-replay", authorId: "u-wei", body: "Are the replays going to cover Klaviyo to Postmark webhook syncs in next week's session?", createdAt: hoursAgo(0.3), status: "pending" },
    { id: "c-pending-5", postId: "p-welcome", authorId: "u-lisa", body: "Just submitted my intake goals. Excited to build repeatable assets instead of chasing social algorithms.", createdAt: hoursAgo(0.2), status: "pending" },
    { id: "c-pending-6", postId: "l-eem-1-1", authorId: "u-marco", body: "What is the recommended warmup schedule for a secondary inbox domain sending 500 emails/day?", createdAt: hoursAgo(0.1), status: "pending" },
  ];

  const courses: Course[] = createClassroomCourses();
  const progress: Database["progress"] = [
    {
      userId: "u-admin",
      courseId: "course-eem-1",
      completedLessonIds: ["l-eem-1-1"],
    },
    {
      userId: "u-member",
      courseId: "course-eem-1",
      completedLessonIds: ["l-eem-1-1"],
    },
  ];

  const events: CalendarEvent[] = [];
  const start = new Date(2026, 6, 1);
  const end = new Date(2027, 2, 31);
  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    const day = d.getDay();
    const y = d.getFullYear();
    const m = d.getMonth() + 1;
    const date = d.getDate();
    if (day === 1) {
      events.push({
        id: `e-live-${y}-${m}-${date}`,
        title: "PSS Live Strategy Call",
        start: atDate(y, m, date, 21, 0),
        end: atDate(y, m, date, 22, 0),
        type: "live",
        description: "Weekly live training, hot seats, and Q&A for the whole community.",
      });
    }
    if (day === 4) {
      events.push({
        id: `e-prem-${y}-${m}-${date}`,
        title: "Premium Mastermind",
        start: atDate(y, m, date, 21, 0),
        end: atDate(y, m, date, 22, 30),
        type: "premium",
        description: "Deep-dive working session for Premium members.",
      });
    }
  }
  events.push({
    id: "e-special-19",
    title: "PSS Live Strategy Call",
    start: atDate(2026, 9, 19, 12, 0),
    end: atDate(2026, 9, 19, 13, 0),
    type: "live",
    description: "Special weekend session — bring a live page for review.",
  });
  events.push({
    id: "e-prem-18",
    title: "Premium Mastermind",
    start: atDate(2026, 9, 18, 22, 30),
    end: atDate(2026, 9, 18, 23, 30),
    type: "premium",
    description: "Extended VIP teardown.",
  });

  const messages: Message[] = [
    { id: "msg1", senderId: "u-ayaan", receiverId: "u-admin", body: "Hi, I specialize in local SEO systems and wanted to introduce myself.", read: false, createdAt: hoursAgo(26) },
    { id: "msg2", senderId: "u-priya", receiverId: "u-admin", body: "What kind of businesses are you seeing win fastest with the method?", read: false, createdAt: hoursAgo(40) },
    { id: "msg3", senderId: "u-admin", receiverId: "u-james", body: "Great win post — can you share the three pages that converted on the next call?", read: true, createdAt: daysAgo(4) },
    { id: "msg4", senderId: "u-sofia", receiverId: "u-admin", body: "Welcome note received. I just finished Start Here.", read: false, createdAt: daysAgo(2) },
    { id: "msg5", senderId: "u-wei", receiverId: "u-admin", body: "Is the Bonus Vault included if I upgrade today?", read: true, createdAt: daysAgo(8) },
    { id: "msg6", senderId: "u-admin", receiverId: "u-wei", body: "Yes — VIP unlocks Bonus Vault immediately, or you can reach Level 2.", read: true, createdAt: daysAgo(8) },
  ];

  const notifications: Notification[] = [
    { id: "n1", userId: "u-admin", actorId: "u-admin", title: "PSS Admin (you) new post", body: "Replay: Skill vs. Shortcut?", link: "/community", read: false, createdAt: hoursAgo(16) },
    { id: "n2", userId: "u-admin", actorId: "u-priya", title: "Priya Sharma new post", body: "How many pages before you promote?", link: "/community", read: false, createdAt: hoursAgo(20) },
    { id: "n3", userId: "u-admin", actorId: "u-james", title: "James Carter posted a win", body: "First inbound clients from the method", link: "/community", read: false, createdAt: daysAgo(13) },
    { id: "n4", userId: "u-admin", actorId: "u-omar", title: "New application pending", body: "Omar Farooq requested to join Permanent Skill Strategy", link: "/admin", read: false, createdAt: hoursAgo(6) },
    { id: "n5", userId: "u-ayaan", actorId: "u-admin", title: "Room is now open", body: "Weekly live call reminder", link: "/calendar", read: true, createdAt: hoursAgo(30) },
  ];

  const reviews: Review[] = [
    { id: "r1", userId: "u-ayaan", rating: 5, body: "I am constantly learning as new modules drop. The team is reactive when you have questions. Great community for building skills that last.", createdAt: daysAgo(20) },
    { id: "r2", userId: "u-james", rating: 5, body: "The method replaced a messy toolbox of tactics. Inbound is slower to start and much stronger after 60 days.", createdAt: daysAgo(14) },
    { id: "r3", userId: "u-priya", rating: 5, body: "Classroom path is clean. Live calls are the unlock. Worth it if you actually do the work.", createdAt: daysAgo(8) },
    { id: "r4", userId: "u-sofia", rating: 5, body: "Finally a system that does not expire when an ad account gets shaken up.", createdAt: daysAgo(5) },
    { id: "r5", userId: "u-amira", rating: 5, body: "VIP mastermind is where my offer got sharp. Highly recommend upgrading if you serve clients.", createdAt: daysAgo(3) },
    { id: "r6", userId: "u-wei", rating: 4, body: "Solid frameworks. I wanted more ecommerce examples — Business Models covered enough to adapt.", createdAt: daysAgo(1) },
  ];

  const sales: Sale[] = [
    { id: "sale1", userId: "u-ayaan", amount: 99, plan: "Business Clarity Course ($99)", createdAt: "2026-03-04T10:10:00.000Z" },
    { id: "sale2", userId: "u-priya", amount: 149, plan: "Learn to Build Apps ($149)", createdAt: "2026-04-18T09:20:00.000Z" },
    { id: "sale3", userId: "u-james", amount: 199, plan: "The Daily Pulse 🔥 VIP Mastermind ($199)", createdAt: "2026-02-11T12:15:00.000Z" },
    { id: "sale4", userId: "u-wei", amount: 89, plan: "n8n Course + Templates ($89)", createdAt: "2026-06-20T08:30:00.000Z" },
    { id: "sale5", userId: "u-amira", amount: 129, plan: "Make.com Course + Templates ($129)", createdAt: "2026-01-28T11:12:00.000Z" },
    { id: "sale6", userId: "u-daniel", amount: 99, plan: "Business Clarity Course ($99)", createdAt: "2026-02-14T11:15:00.000Z" },
  ];

  const communities: Community[] = [
    {
      id: "comm-ai-architects",
      name: "AI Architects",
      slug: "ai-architects",
      description: "Elite mastermind for AI systems architects, full-stack agent developers, and digital operators.",
      icon: "/logo.png",
      isPrivate: false,
      memberCount: 168,
      onlineCount: 8,
      adminCount: 1,
      type: "students",
      createdAt: "2025-01-12T08:00:00.000Z",
      createdBy: "u-admin",
    },
    {
      id: "comm-students",
      name: "Students",
      slug: "students",
      description: "Official learning hub for Permanent Skills Academy students. Master durable skills, AI automations, systems architecture, and compounded growth playbooks.",
      icon: "/logo.png",
      isPrivate: false,
      memberCount: 128,
      onlineCount: 5,
      adminCount: 1,
      type: "students",
      createdAt: "2025-01-12T08:00:00.000Z",
      createdBy: "u-admin",
    },
    {
      id: "comm-team",
      name: "Team Members",
      slug: "team-members",
      description: "Private internal hub for team specialists and staff members. Watch training modules, review SOPs, participate in discussions, and record workflow notes.",
      icon: "/team-icon.png",
      isPrivate: true,
      memberCount: 24,
      onlineCount: 3,
      adminCount: 1,
      type: "team",
      createdAt: "2026-02-10T10:00:00.000Z",
      createdBy: "u-admin",
    },
  ];

  const projects: Project[] = [
    {
      id: "proj-nexus",
      title: "Nexus Design System 2.0",
      description: "Consolidating token architecture, multi-brand themes, accessible data tables, and high-frequency Figma token pipeline.",
      version: "v2.4.0",
      leadId: "u-sofia",
      leadName: "Sarah K.",
      memberIds: ["u-sofia", "u-james", "u-amira", "u-wei", "u-priya", "u-ayaan"],
      mentionedUsernames: ["sofia-alvarez", "james-carter", "amira-tariq"],
      progress: 75,
      tasks: [
        { id: "t1", title: "Consolidate token architecture & color variables", completed: true },
        { id: "t2", title: "Implement dark/light theme switching tokens", completed: true },
        { id: "t3", title: "Accessible high-frequency Figma token pipeline sync", completed: true },
        { id: "t4", title: "WCAG 2.2 AA Contrast audit & cross-team documentation", completed: false },
      ],
      status: "active",
      meetSyncTime: "Sprint Sync: Today, 3:00 PM",
      meetRoom: "Nexus Meet #room-design",
      meetUrl: "https://meet.google.com/new",
      createdAt: daysAgo(5),
      createdBy: "u-admin",
    },
    {
      id: "proj-seo-cluster",
      title: "Programmatic SEO Topic Cluster Pipeline",
      description: "High-yield permanent skill content structure with automated internal link graph validation.",
      version: "v1.2.0",
      leadId: "u-james",
      leadName: "James Carter",
      memberIds: ["u-james", "u-hana", "u-admin"],
      mentionedUsernames: ["james-carter", "hana-kim"],
      progress: 67,
      tasks: [
        { id: "t5", title: "Keyword entity clustering schema mapping", completed: true },
        { id: "t6", title: "Automated internal linking graph validation", completed: true },
        { id: "t7", title: "Publish pilot 20 evergreen topical hubs", completed: false },
      ],
      status: "active",
      meetSyncTime: "Weekly Review: Friday, 4:30 PM",
      meetRoom: "Growth Meet #cluster-review",
      meetUrl: "https://meet.google.com/new",
      createdAt: daysAgo(10),
      createdBy: "u-admin",
    },
    {
      id: "proj-crm-engine",
      title: "Omnichannel Lead Nurture & CRM Engine",
      description: "Automated multi-touch outreach architecture, high-intent lead scoring, and N8N pipeline integration with real-time conversion telemetry.",
      version: "v1.0.0",
      leadId: "u-ayaan",
      leadName: "Ayaan Malik",
      memberIds: ["u-ayaan", "u-priya", "u-admin"],
      mentionedUsernames: ["ayaan-malik", "priya-sharma"],
      progress: 100,
      tasks: [
        { id: "t8", title: "N8N Webhook payload normalization", completed: true },
        { id: "t9", title: "Lead scoring matrix configuration", completed: true },
        { id: "t10", title: "Multi-channel automated sequence deployment", completed: true },
      ],
      status: "completed",
      meetSyncTime: "Sprint Wrap-Up: Completed",
      meetRoom: "Archive Meet #crm-wrapup",
      meetUrl: "https://meet.google.com/new",
      createdAt: daysAgo(28),
      createdBy: "u-admin",
    },
  ];

  const videoResources: VideoResource[] = [
    {
      id: "vid-overview-1",
      title: "REAL STATS — Community Overview & Framework",
      description: "Comprehensive walkthrough of the Permanent Skill architecture, daily cadence, and mastermind systems.",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      thumbnailUrl: "",
      duration: "12:45",
      category: "overview",
      isPublic: true,
      isFeatured: true,
      viewCount: 245,
      createdAt: daysAgo(30),
    },
    {
      id: "vid-mastermind-1",
      title: "Mastermind Strategy Teardown & High-Ticket Offers",
      description: "Deep dive into value pricing, client onboarding automation, and multi-tier retargeting.",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      duration: "45:10",
      category: "mastermind",
      isPublic: false,
      isFeatured: false,
      viewCount: 189,
      createdAt: daysAgo(14),
    },
    {
      id: "vid-tutorial-1",
      title: "n8n Webhook Architecture & Make.com Blueprint Setup",
      description: "Technical build of scalable lead ingestion and CRM sync workflows.",
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      duration: "24:30",
      category: "tutorials",
      isPublic: true,
      isFeatured: false,
      viewCount: 310,
      createdAt: daysAgo(7),
    },
  ];

  return {
    users,
    posts,
    comments,
    courses,
    progress,
    events,
    projects,
    messages,
    notifications,
    reviews,
    sales,
    sessions: [],
    communities,
    videoResources,
  };
}
