import { hashPassword } from "./password";
import type {
  CalendarEvent,
  Comment,
  Community,
  Course,
  Database,
  Message,
  Notification,
  Post,
  Project,
  Review,
  Sale,
  User,
} from "./types";

export const COURSE_CATALOG_IDS = [
  "course-seo",
  "course-ai-seo",
  "course-ai",
  "course-n8n",
  "course-meta-ads",
  "course-leads",
] as const;

export const OLD_COURSE_IDS = [
  "course-start",
  "course-method",
  "course-models",
  "course-toolkit",
  "course-calls",
  "course-bonus",
];

export function createClassroomCourses(): Course[] {
  return [
    {
      id: "course-seo",
      slug: "semantic-seo",
      title: "Semantic SEO Course",
      description: "Build topical authority with semantic SEO — entities, intent, and pages that keep ranking.",
      accent: "from-primary-dark via-primary to-[#7c83ff]",
      badge: "SEMANTIC SEO",
      unlockLevel: 1,
      price: 49,
      lessons: [
        {
          id: "l-1-1",
          module: "Module 1: Introduction",
          title: "1.1 Introduction and Course Overview",
          videoTitle: "1.1 Introduction and Course Overview",
          duration: "4:12",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "High-level roadmap of the system, setting up your workspace, and understanding core compounding mechanics.\n\n- Entity search fundamentals\n- Topical authority vs isolated keywords\n- Compounding content infrastructure",
        },
        {
          id: "l-1-2",
          module: "Module 1: Introduction",
          title: "1.2 Why Email Marketing? Benefits, Goals",
          videoTitle: "1.2 Why Email Marketing? Benefits, Goals",
          duration: "6:45",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Why owned channels dominate paid traffic and how to build permanent audience assets that convert consistently.",
        },
        {
          id: "l-2-1",
          module: "Module 2: Core Strategy",
          title: "2.1 Niche Selection & Keyword Moats",
          videoTitle: "2.1 Niche Selection & Keyword Moats",
          duration: "5:20",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Identify asymmetric niche opportunities with high transactional intent and minimal domain rating requirements.",
        },
        {
          id: "l-2-2",
          module: "Module 2: Core Strategy",
          title: "2.2 Building High-Converting Funnel Pages",
          videoTitle: "2.2 Building High-Converting Funnel Pages",
          duration: "7:10",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Constructing high-converting landing pages that capture organic traffic and convert visitors into long-term subscribers.",
        },
      ],
    },
    {
      id: "course-ai-seo",
      slug: "ai-seo",
      title: "AI SEO Systems",
      description: "Use AI to research, draft, and scale SEO systems without losing quality or ownership.",
      accent: "from-primary-dark via-primary to-[#7c83ff]",
      badge: "AI SEO",
      unlockLevel: 1,
      price: 59,
      lessons: [
        {
          id: "l-ai-1",
          module: "Module 1: Introduction",
          title: "1.1 AI Keyword Clustering & Topical Maps",
          videoTitle: "1.1 AI Keyword Clustering & Topical Maps",
          duration: "5:30",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Clustering raw SERP entities into cohesive, non-cannibalizing content silos.\n\n- Entity extraction pipelines\n- Search intent cluster mapping\n- Avoiding keyword cannibalization",
        },
        {
          id: "l-ai-2",
          module: "Module 1: Introduction",
          title: "1.2 Automated Content Graph Validation",
          videoTitle: "1.2 Automated Content Graph Validation",
          duration: "8:15",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Automated programmatic validation of internal linking structure prior to site indexing.\n\n- Anchor text distribution\n- PageRank flow simulation\n- Automated orphan page detection",
        },
        {
          id: "l-ai-2-1",
          module: "Module 2: Agent Workflows",
          title: "2.1 Autonomous Agent Content Workflows",
          videoTitle: "2.1 Autonomous Agent Content Workflows",
          duration: "6:40",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Deploying multi-step LLM chains with schema validation and fact-checking safeguards.",
        },
        {
          id: "l-ai-2-2",
          module: "Module 2: Agent Workflows",
          title: "2.2 Scaling Indexation & Schema Pipelines",
          videoTitle: "2.2 Scaling Indexation & Schema Pipelines",
          duration: "9:05",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Direct API submission to Google Search Console and automated JSON-LD entity graph generation.",
        },
      ],
    },
    {
      id: "course-ai",
      slug: "ai-web-software-tools",
      title: "AI Web, Software, and Tool Creation",
      description: "Create websites, software, and tools with AI so you can ship products and client work faster.",
      accent: "from-primary-dark via-primary to-[#7c83ff]",
      badge: "AI TOOLS",
      unlockLevel: 1,
      price: 79,
      lessons: [
        {
          id: "l-tools-1",
          module: "Module 1: Quickstart",
          title: "1.1 Prompt to Fullstack App in 10 Minutes",
          videoTitle: "1.1 Prompt to Fullstack App in 10 Minutes",
          duration: "10:15",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Step-by-step walk through generating complete SaaS prototypes using state of the art models.",
        },
        {
          id: "l-tools-2",
          module: "Module 1: Quickstart",
          title: "1.2 Connecting Database and APIs with AI",
          videoTitle: "1.2 Connecting Database and APIs with AI",
          duration: "12:00",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Production patterns for environment variables, serverless databases, and webhook triggers.",
        },
        {
          id: "l-tools-2-1",
          module: "Module 2: Advanced Tool Architecture",
          title: "2.1 Building Embeddable Free Lead Tools",
          videoTitle: "2.1 Building Embeddable Free Lead Tools",
          duration: "14:20",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Constructing high-converting interactive calculators and generators that rank and acquire users on autopilot.",
        },
      ],
    },
    {
      id: "course-n8n",
      slug: "n8n-automation",
      title: "N8N Automation",
      description: "Automate lead flow, follow-ups, and operations with N8N workflows.",
      accent: "from-primary-dark via-primary to-[#7c83ff]",
      badge: "N8N",
      unlockLevel: 1,
      price: 69,
      lessons: [
        {
          id: "l-n8n-1-1",
          module: "Module 1: Foundations",
          title: "1.1 N8N Infrastructure & Webhook Setup",
          videoTitle: "1.1 N8N Infrastructure & Webhook Setup",
          duration: "6:15",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Setting up your N8N environment, securing endpoints, and structuring inbound webhook data pipelines.",
        },
        {
          id: "l-n8n-1-2",
          module: "Module 1: Foundations",
          title: "1.2 Data Transformation & Error Handling",
          videoTitle: "1.2 Data Transformation & Error Handling",
          duration: "8:40",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Handling JSON schemas, formatting nested data, and setting up real-time failure alerts.",
        },
        {
          id: "l-n8n-2-1",
          module: "Module 2: Production Automations",
          title: "2.1 Automated CRM Lead Routing & Scoring",
          videoTitle: "2.1 Automated CRM Lead Routing & Scoring",
          duration: "9:30",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Instant webhook enrichment, automated qualification checks, and team notification triggers.",
        },
        {
          id: "l-n8n-2-2",
          module: "Module 2: Production Automations",
          title: "2.2 Multi-Agent AI Pipelines in N8N",
          videoTitle: "2.2 Multi-Agent AI Pipelines in N8N",
          duration: "11:10",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Orchestrating OpenAI / Claude nodes, vector database memory, and dynamic prompt routing in N8N.",
        },
      ],
    },
    {
      id: "course-meta-ads",
      slug: "meta-ads",
      title: "Meta Ads",
      description: "Research, creative, campaign setup, and scaling on Meta ads.",
      accent: "from-primary-dark via-primary to-[#7c83ff]",
      badge: "META ADS",
      unlockLevel: 1,
      price: 89,
      lessons: [
        {
          id: "l-meta-1-1",
          module: "Module 1: Creative & Angles",
          title: "1.1 Competitor Ad Teardowns & Angle Research",
          videoTitle: "1.1 Competitor Ad Teardowns & Angle Research",
          duration: "7:25",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Reverse-engineering top-spending competitor ads to identify winning hooks and emotional angles.",
        },
        {
          id: "l-meta-1-2",
          module: "Module 1: Creative & Angles",
          title: "1.2 High-CTR Creative Frameworks & UGC",
          videoTitle: "1.2 High-CTR Creative Frameworks & UGC",
          duration: "9:15",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Scripting and producing UGC-style video ads that achieve low CPCs and high view-through rates.",
        },
        {
          id: "l-meta-2-1",
          module: "Module 2: Media Buying & Scaling",
          title: "2.1 CBO vs ABO & Broad Targeting Setup",
          videoTitle: "2.1 CBO vs ABO & Broad Targeting Setup",
          duration: "10:45",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Setting up clean account architecture that scales without ad fatigue or audience fragmentation.",
        },
        {
          id: "l-meta-2-2",
          module: "Module 2: Media Buying & Scaling",
          title: "2.2 ROAS Optimization & Retargeting Loops",
          videoTitle: "2.2 ROAS Optimization & Retargeting Loops",
          duration: "8:50",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Attribution modeling, custom audience exclusion rules, and automated budget scaling rules.",
        },
      ],
    },
    {
      id: "course-leads",
      slug: "leads-generation",
      title: "Leads Generation",
      description: "Offers, funnels, and follow-up systems that generate qualified leads.",
      accent: "from-primary-dark via-primary to-[#7c83ff]",
      badge: "LEADS",
      unlockLevel: 1,
      price: 99,
      lessons: [
        {
          id: "l-leads-1-1",
          module: "Module 1: Offer & Lead Magnet",
          title: "1.1 Engineering High-Converting Lead Magnets",
          videoTitle: "1.1 Engineering High-Converting Lead Magnets",
          duration: "6:50",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Crafting irresistible value-first lead assets that attract decision-makers and high-ticket buyers.",
        },
        {
          id: "l-leads-1-2",
          module: "Module 1: Offer & Lead Magnet",
          title: "1.2 High-Converting Funnel Architecture",
          videoTitle: "1.2 High-Converting Funnel Architecture",
          duration: "8:30",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Optin pages, VSL structures, application forms, and one-click calendar booking mechanics.",
        },
        {
          id: "l-leads-2-1",
          module: "Module 2: Nurture & Conversion",
          title: "2.1 Automated Email Sequences & Lead Scoring",
          videoTitle: "2.1 Automated Email Sequences & Lead Scoring",
          duration: "9:10",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Email nurture flows that build intense trust and convert cold leads into booked discovery calls.",
        },
        {
          id: "l-leads-2-2",
          module: "Module 2: Nurture & Conversion",
          title: "2.2 Call Closing & Pipeline Management",
          videoTitle: "2.2 Call Closing & Pipeline Management",
          duration: "11:40",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          notes: "Frameworks for handling objections, structuring proposals, and tracking deal velocity across your CRM.",
        },
      ],
    },
  ];
}

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 3600 * 1000).toISOString();
}

function daysAgo(days: number) {
  return hoursAgo(days * 24);
}

function atDate(year: number, month: number, day: number, hour = 21, minute = 0) {
  return new Date(year, month - 1, day, hour, minute, 0).toISOString();
}

export function createSeed(): Database {
  const adminHash = hashPassword("admin@permanentseo.com");
  const memberHash = hashPassword("member123");

  const users: User[] = [
    {
      id: "u-admin",
      email: "admin@permanentseo.com",
      passwordHash: adminHash,
      name: "PSS Admin",
      username: "pss-admin",
      bio: "Founder of Permanent Skill Strategy. We help professionals build skills that compound for decades.",
      role: "admin",
      status: "approved",
      points: 540,
      points7d: 22,
      points30d: 86,
      avatarColor: "#5051F9",
      location: "Dubai, UAE",
      lat: 25.2048,
      lng: 55.2708,
      joinedAt: "2025-01-12T08:00:00.000Z",
      lastSeenAt: new Date().toISOString(),
      loginCount: 186,
      isPremium: true,
      language: "English",
      ipAddress: "192.168.1.1",
      affiliateCode: "PSS-ADMIN",
      affiliateClicks: 128,
      affiliateSignups: 14,
      affiliateEarnings: 126,
    },
    {
      id: "u-ayaan",
      email: "ayaan@example.com",
      passwordHash: memberHash,
      name: "Ayaan Malik",
      username: "ayaan-malik",
      bio: "SEO specialist helping local brands rank with durable content systems.",
      role: "member",
      status: "approved",
      points: 168,
      points7d: 19,
      points30d: 114,
      avatarColor: "#0ea5e9",
      location: "Karachi, Pakistan",
      lat: 24.8607,
      lng: 67.0011,
      joinedAt: "2026-03-04T10:00:00.000Z",
      lastSeenAt: hoursAgo(0.2),
      loginCount: 64,
      isPremium: true,
      language: "English",
      ipAddress: "182.185.120.45",
      affiliateCode: "PSS-AYAAN",
      affiliateClicks: 22,
      affiliateSignups: 3,
      affiliateEarnings: 27,
    },
    {
      id: "u-priya",
      email: "priya@example.com",
      passwordHash: memberHash,
      name: "Priya Sharma",
      username: "priya-sharma",
      bio: "Content strategist. I turn one idea into months of search-ready assets.",
      role: "member",
      status: "approved",
      points: 102,
      points7d: 12,
      points30d: 28,
      avatarColor: "#db2777",
      location: "Mumbai, India",
      lat: 19.076,
      lng: 72.8777,
      joinedAt: "2026-04-18T09:00:00.000Z",
      lastSeenAt: hoursAgo(1),
      loginCount: 41,
      isPremium: true,
      language: "English",
      ipAddress: "103.212.144.18",
      affiliateCode: "PSS-PRIYA",
      affiliateClicks: 9,
      affiliateSignups: 1,
      affiliateEarnings: 9,
    },
    {
      id: "u-james",
      email: "james@example.com",
      passwordHash: memberHash,
      name: "James Carter",
      username: "james-carter",
      bio: "Agency owner. Building retainers around permanent skill systems, not one-off tactics.",
      role: "member",
      status: "approved",
      points: 122,
      points7d: 8,
      points30d: 23,
      avatarColor: "#16a34a",
      location: "London, UK",
      lat: 51.5074,
      lng: -0.1278,
      joinedAt: "2026-02-11T12:00:00.000Z",
      lastSeenAt: hoursAgo(4),
      loginCount: 73,
      isPremium: true,
      language: "English",
      ipAddress: "82.165.197.1",
      affiliateCode: "PSS-JAMES",
      affiliateClicks: 31,
      affiliateSignups: 4,
      affiliateEarnings: 36,
    },
    {
      id: "u-sofia",
      email: "sofia@example.com",
      passwordHash: memberHash,
      name: "Sofia Alvarez",
      username: "sofia-alvarez",
      bio: "Coach for consultants who want inbound that still works in 3 years.",
      role: "member",
      status: "approved",
      points: 98,
      points7d: 6,
      points30d: 21,
      avatarColor: "#7c3aed",
      location: "Austin, USA",
      lat: 30.2672,
      lng: -97.7431,
      joinedAt: "2026-05-02T15:00:00.000Z",
      lastSeenAt: hoursAgo(26),
      loginCount: 29,
      isPremium: false,
      language: "English",
      ipAddress: "104.28.19.102",
      affiliateCode: "PSS-SOFIA",
      affiliateClicks: 4,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-wei",
      email: "wei@example.com",
      passwordHash: memberHash,
      name: "Chen Wei",
      username: "chen-wei",
      bio: "Ecommerce operator applying authority SEO to product education hubs.",
      role: "member",
      status: "approved",
      points: 67,
      points7d: 7,
      points30d: 15,
      avatarColor: "#ea580c",
      location: "Singapore",
      lat: 1.3521,
      lng: 103.8198,
      joinedAt: "2026-06-20T08:00:00.000Z",
      lastSeenAt: hoursAgo(3),
      loginCount: 18,
      isPremium: true,
      language: "English",
      ipAddress: "118.189.201.33",
      affiliateCode: "PSS-WEI",
      affiliateClicks: 6,
      affiliateSignups: 1,
      affiliateEarnings: 9,
    },
    {
      id: "u-amira",
      email: "amira@example.com",
      passwordHash: memberHash,
      name: "Amira Hassan",
      username: "amira-hassan",
      bio: "Consultant helping service businesses become the obvious search answer.",
      role: "member",
      status: "approved",
      points: 63,
      points7d: 4,
      points30d: 13,
      avatarColor: "#0891b2",
      location: "Dubai, UAE",
      lat: 25.2769,
      lng: 55.2962,
      joinedAt: "2026-01-28T11:00:00.000Z",
      lastSeenAt: hoursAgo(8),
      loginCount: 52,
      isPremium: true,
      language: "English",
      ipAddress: "94.200.12.180",
      affiliateCode: "PSS-AMIRA",
      affiliateClicks: 11,
      affiliateSignups: 2,
      affiliateEarnings: 18,
    },
    {
      id: "u-noah",
      email: "noah@example.com",
      passwordHash: memberHash,
      name: "Noah Bennett",
      username: "noah-bennett",
      bio: "Freelance strategist. Here to replace random tactics with a repeatable system.",
      role: "member",
      status: "approved",
      points: 58,
      points7d: 4,
      points30d: 12,
      avatarColor: "#4f46e5",
      location: "Sydney, Australia",
      lat: -33.8688,
      lng: 151.2093,
      joinedAt: "2026-07-09T07:00:00.000Z",
      lastSeenAt: hoursAgo(12),
      loginCount: 21,
      isPremium: false,
      language: "English",
      ipAddress: "139.130.4.5",
      affiliateCode: "PSS-NOAH",
      affiliateClicks: 2,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-lisa",
      email: "lisa@example.com",
      passwordHash: memberHash,
      name: "Lisa Okonkwo",
      username: "lisa-okonkwo",
      bio: "Brand strategist pairing positioning with search intent.",
      role: "member",
      status: "approved",
      points: 44,
      points7d: 3,
      points30d: 8,
      avatarColor: "#be123c",
      location: "Lagos, Nigeria",
      lat: 6.5244,
      lng: 3.3792,
      joinedAt: "2026-08-01T13:00:00.000Z",
      lastSeenAt: hoursAgo(30),
      loginCount: 14,
      isPremium: false,
      language: "English",
      ipAddress: "102.89.23.11",
      affiliateCode: "PSS-LISA",
      affiliateClicks: 1,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-marco",
      email: "marco@example.com",
      passwordHash: memberHash,
      name: "Marco Rossi",
      username: "marco-rossi",
      bio: "Local SEO for multi-location service brands across Europe.",
      role: "member",
      status: "approved",
      points: 36,
      points7d: 2,
      points30d: 6,
      avatarColor: "#0f766e",
      location: "Milan, Italy",
      lat: 45.4642,
      lng: 9.19,
      joinedAt: "2026-08-14T16:00:00.000Z",
      lastSeenAt: hoursAgo(50),
      loginCount: 11,
      isPremium: false,
      language: "English",
      ipAddress: "151.48.90.14",
      affiliateCode: "PSS-MARCO",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-hana",
      email: "hana@example.com",
      passwordHash: memberHash,
      name: "Hana Kim",
      username: "hana-kim",
      bio: "Technical SEO and information architecture for growing publications.",
      role: "member",
      status: "approved",
      points: 12,
      points7d: 5,
      points30d: 12,
      avatarColor: "#9333ea",
      location: "Seoul, South Korea",
      lat: 37.5665,
      lng: 126.978,
      joinedAt: daysAgo(12),
      lastSeenAt: hoursAgo(6),
      loginCount: 7,
      isPremium: false,
      language: "English",
      ipAddress: "211.234.118.9",
      affiliateCode: "PSS-HANA",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
    },
    {
      id: "u-omar",
      email: "omar@example.com",
      passwordHash: memberHash,
      name: "Omar Farooq",
      username: "omar-farooq",
      bio: "Learning a durable skill stack for my consulting practice.",
      role: "member",
      status: "pending",
      points: 0,
      points7d: 0,
      points30d: 0,
      avatarColor: "#64748b",
      location: "Lahore, Pakistan",
      lat: 31.5204,
      lng: 74.3587,
      joinedAt: hoursAgo(6),
      lastSeenAt: hoursAgo(6),
      loginCount: 1,
      isPremium: false,
      language: "English",
      ipAddress: "39.40.18.22",
      affiliateCode: "PSS-OMAR",
      affiliateClicks: 0,
      affiliateSignups: 0,
      affiliateEarnings: 0,
      application: {
        fullName: "Omar Farooq",
        phone: "+92 300 5550199",
        country: "Pakistan",
        city: "Lahore",
        profession: "Independent consultant",
        experience: "2-4 years",
        website: "https://omarfarooq.co",
        goals: "I want a repeatable SEO and skill system so my pipeline is not dependent on referrals.",
        howHeard: "A colleague in the community",
        notes: "Independent consultant with a few years of SEO work. Looking for a durable system.",
      },
    },
  ];

  const posts: Post[] = [
    {
      id: "p-replay",
      authorId: "u-admin",
      category: "recorded",
      title: "Replay: Skill vs. Shortcut?",
      body: "In this session we run community Q&A. We cover why durable skills beat rented traffic, how to pick one offer, and what to do when a tactic stops working. Watch the replay and drop questions below.",
      pinned: true,
      likes: ["u-ayaan", "u-priya", "u-james"],
      createdAt: hoursAgo(16),
      thumbnail: "replay",
    },
    {
      id: "p-win",
      authorId: "u-james",
      category: "wins",
      title: "First inbound clients from the method",
      body: "Launched the authority pages last month and was skeptical it would actually compound. Closed 3 inbound clients this week. Pipeline finally feels like an asset, not a gamble.",
      pinned: true,
      likes: ["u-admin", "u-ayaan", "u-sofia", "u-wei", "u-amira"],
      createdAt: daysAgo(13),
    },
    {
      id: "p-welcome",
      authorId: "u-admin",
      category: "chat",
      title: "Welcome 👋",
      body: "Welcome to Permanent Skill Strategy. So happy you are here. Whether you are brand new or already running offers, start with the Classroom path, introduce yourself below, and come to the next live call.",
      pinned: true,
      likes: ["u-priya", "u-noah", "u-hana"],
      createdAt: "2025-10-25T09:00:00.000Z",
    },
    {
      id: "p-chat-1",
      authorId: "u-priya",
      category: "chat",
      title: "How many pages before you promote?",
      body: "I have 8 supporting articles and 1 pillar. Is that enough to start internal linking in earnest, or should I wait until 15?",
      pinned: false,
      likes: ["u-ayaan", "u-hana"],
      createdAt: hoursAgo(20),
    },
    {
      id: "p-win-2",
      authorId: "u-sofia",
      category: "wins",
      title: "Booked my calendar from organic",
      body: "Two discovery calls this week came from a single case-study page I built using the Start Here module. Small win, but it feels different from chasing likes.",
      pinned: false,
      likes: ["u-james", "u-amira", "u-admin"],
      createdAt: daysAgo(2),
    },
    {
      id: "p-review",
      authorId: "u-ayaan",
      category: "reviews",
      title: "Clear system, not hype",
      body: "I have been through a lot of tactic-heavy trainings. This is the first one that treats skills like an asset. The live calls are practical and the classroom path is easy to follow.",
      pinned: false,
      likes: ["u-admin", "u-james"],
      createdAt: daysAgo(9),
    },
    {
      id: "p-recorded-2",
      authorId: "u-admin",
      category: "recorded",
      title: "Replay: Offer architecture workshop",
      body: "We mapped four business models onto the same skill system: coaching, productized service, education, and local. Recording is in Archived Calls.",
      pinned: false,
      likes: ["u-wei", "u-marco"],
      createdAt: daysAgo(6),
      thumbnail: "workshop",
    },
    {
      id: "p-chat-2",
      authorId: "u-hana",
      category: "chat",
      title: "Intro — technical SEO + publishing",
      body: "Hi everyone. I work on information architecture for publications. Excited to apply the Permanent Skill Method to topic clusters instead of one-off posts.",
      pinned: false,
      likes: ["u-priya"],
      createdAt: daysAgo(1),
    },
  ];

  const comments: Comment[] = [
    { id: "c1", postId: "p-replay", authorId: "u-ayaan", body: "The section on rented vs owned attention was excellent.", createdAt: hoursAgo(14), status: "approved" },
    { id: "c2", postId: "p-replay", authorId: "u-priya", body: "Can we get the offer worksheet from the call in Toolkit?", createdAt: hoursAgo(12), status: "approved" },
    { id: "c3", postId: "p-replay", authorId: "u-james", body: "Watching with my team tomorrow. Thank you.", createdAt: hoursAgo(10), status: "approved" },
    { id: "c4", postId: "p-win", authorId: "u-admin", body: "This is the compounding we talk about. Document the pages that converted.", createdAt: daysAgo(12), status: "approved" },
    { id: "c5", postId: "p-win", authorId: "u-sofia", body: "Congrats James. Which cluster was the first client from?", createdAt: daysAgo(12), status: "approved" },
    { id: "c6", postId: "p-welcome", authorId: "u-noah", body: "Glad to be here. Starting the classroom tonight.", createdAt: daysAgo(20), status: "approved" },
    { id: "c7", postId: "p-chat-1", authorId: "u-admin", body: "Ship the 8, interlink tightly, then add. Waiting for a magic number usually delays learning.", createdAt: hoursAgo(18), status: "approved" },
    { id: "c8", postId: "p-win-2", authorId: "u-amira", body: "Love this. Case studies are underrated authority assets.", createdAt: daysAgo(1), status: "approved" },
  ];

  const courses: Course[] = createClassroomCourses();
  const progress: Database["progress"] = [];

  const events: CalendarEvent[] = [];
  const start = new Date(2026, 7, 31);
  const end = new Date(2026, 9, 6);
  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    const day = d.getDay();
    const y = d.getFullYear();
    const m = d.getMonth() + 1;
    const date = d.getDate();
    if (day === 1) {
      events.push({
        id: `e-live-${y}-${m}-${date}`,
        title: "PSS Live Strategy Call",
        start: atDate(y, m, date, 21, 0),
        end: atDate(y, m, date, 22, 0),
        type: "live",
        description: "Weekly live training, hot seats, and Q&A for the whole community.",
      });
    }
    if (day === 4) {
      events.push({
        id: `e-prem-${y}-${m}-${date}`,
        title: "Premium Mastermind",
        start: atDate(y, m, date, 21, 0),
        end: atDate(y, m, date, 22, 30),
        type: "premium",
        description: "Deep-dive working session for Premium members.",
      });
    }
  }
  events.push({
    id: "e-special-19",
    title: "PSS Live Strategy Call",
    start: atDate(2026, 9, 19, 12, 0),
    end: atDate(2026, 9, 19, 13, 0),
    type: "live",
    description: "Special weekend session — bring a live page for review.",
  });
  events.push({
    id: "e-prem-18",
    title: "Premium Mastermind",
    start: atDate(2026, 9, 18, 22, 30),
    end: atDate(2026, 9, 18, 23, 30),
    type: "premium",
    description: "Extended premium teardown.",
  });

  const messages: Message[] = [
    { id: "msg1", senderId: "u-ayaan", receiverId: "u-admin", body: "Hi, I specialize in local SEO systems and wanted to introduce myself.", read: false, createdAt: hoursAgo(26) },
    { id: "msg2", senderId: "u-priya", receiverId: "u-admin", body: "What kind of businesses are you seeing win fastest with the method?", read: false, createdAt: hoursAgo(40) },
    { id: "msg3", senderId: "u-admin", receiverId: "u-james", body: "Great win post — can you share the three pages that converted on the next call?", read: true, createdAt: daysAgo(4) },
    { id: "msg4", senderId: "u-sofia", receiverId: "u-admin", body: "Welcome note received. I just finished Start Here.", read: false, createdAt: daysAgo(2) },
    { id: "msg5", senderId: "u-wei", receiverId: "u-admin", body: "Is the Bonus Vault included if I upgrade today?", read: true, createdAt: daysAgo(8) },
    { id: "msg6", senderId: "u-admin", receiverId: "u-wei", body: "Yes — Premium unlocks Bonus Vault immediately, or you can reach Level 2.", read: true, createdAt: daysAgo(8) },
  ];

  const notifications: Notification[] = [
    { id: "n1", userId: "u-admin", actorId: "u-admin", title: "PSS Admin (you) new post", body: "Replay: Skill vs. Shortcut?", link: "/community", read: false, createdAt: hoursAgo(16) },
    { id: "n2", userId: "u-admin", actorId: "u-priya", title: "Priya Sharma new post", body: "How many pages before you promote?", link: "/community", read: false, createdAt: hoursAgo(20) },
    { id: "n3", userId: "u-admin", actorId: "u-james", title: "James Carter posted a win", body: "First inbound clients from the method", link: "/community", read: false, createdAt: daysAgo(13) },
    { id: "n4", userId: "u-admin", actorId: "u-omar", title: "New application pending", body: "Omar Farooq requested to join Permanent Skill Strategy", link: "/admin", read: false, createdAt: hoursAgo(6) },
    { id: "n5", userId: "u-ayaan", actorId: "u-admin", title: "Room is now open", body: "Weekly live call reminder", link: "/calendar", read: true, createdAt: hoursAgo(30) },
  ];

  const reviews: Review[] = [
    { id: "r1", userId: "u-ayaan", rating: 5, body: "I am constantly learning as new modules drop. The team is reactive when you have questions. Great community for building skills that last.", createdAt: daysAgo(20) },
    { id: "r2", userId: "u-james", rating: 5, body: "The method replaced a messy toolbox of tactics. Inbound is slower to start and much stronger after 60 days.", createdAt: daysAgo(14) },
    { id: "r3", userId: "u-priya", rating: 5, body: "Classroom path is clean. Live calls are the unlock. Worth it if you actually do the work.", createdAt: daysAgo(8) },
    { id: "r4", userId: "u-sofia", rating: 5, body: "Finally a system that does not expire when an ad account gets shaken up.", createdAt: daysAgo(5) },
    { id: "r5", userId: "u-amira", rating: 5, body: "Premium mastermind is where my offer got sharp. Highly recommend upgrading if you serve clients.", createdAt: daysAgo(3) },
    { id: "r6", userId: "u-wei", rating: 4, body: "Solid frameworks. I wanted more ecommerce examples — Business Models covered enough to adapt.", createdAt: daysAgo(1) },
  ];

  const sales: Sale[] = [
    { id: "sale1", userId: "u-ayaan", amount: 9, plan: "Premium monthly", createdAt: "2026-03-04T10:10:00.000Z" },
    { id: "sale2", userId: "u-priya", amount: 9, plan: "Premium monthly", createdAt: "2026-04-18T09:20:00.000Z" },
    { id: "sale3", userId: "u-james", amount: 9, plan: "Premium monthly", createdAt: "2026-02-11T12:15:00.000Z" },
    { id: "sale4", userId: "u-wei", amount: 9, plan: "Premium monthly", createdAt: "2026-06-20T08:30:00.000Z" },
    { id: "sale5", userId: "u-amira", amount: 9, plan: "Premium monthly", createdAt: "2026-01-28T11:12:00.000Z" },
    { id: "sale6", userId: "u-admin", amount: 9, plan: "Founder", createdAt: "2025-01-12T08:00:00.000Z" },
  ];

  const communities: Community[] = [
    {
      id: "comm-pss",
      name: "Permanent Skill Strategy",
      slug: "permanent-skill-strategy",
      description: "Private community for durable SEO, automation, and compounded skill systems.",
      icon: "/logo.png",
      isPrivate: true,
      memberCount: 12,
      createdAt: "2025-01-12T08:00:00.000Z",
      createdBy: "u-admin",
    },
    {
      id: "comm-ai-lab",
      name: "AI & Automation Lab",
      slug: "ai-automation-lab",
      description: "Workflows, N8N templates, and AI agents built for real business automation.",
      isPrivate: false,
      memberCount: 8,
      createdAt: "2026-02-10T10:00:00.000Z",
      createdBy: "u-admin",
    },
    {
      id: "comm-growth-hub",
      name: "Growth & Client Acquisition",
      slug: "growth-client-acquisition",
      description: "Proven funnels, outreach frameworks, and lead generation mastery.",
      isPrivate: true,
      memberCount: 5,
      createdAt: "2026-03-01T12:00:00.000Z",
      createdBy: "u-admin",
    },
  ];

  const projects: Project[] = [
    {
      id: "proj-nexus",
      title: "Nexus Design System 2.0",
      description: "Consolidating token architecture, multi-brand themes, accessible data tables, and high-frequency Figma token pipeline.",
      version: "v2.4.0",
      leadId: "u-sofia",
      leadName: "Sarah K.",
      memberIds: ["u-sofia", "u-james", "u-amira", "u-wei", "u-priya", "u-ayaan"],
      mentionedUsernames: ["sofia-alvarez", "james-carter", "amira-tariq"],
      progress: 75,
      tasks: [
        { id: "t1", title: "Consolidate token architecture & color variables", completed: true },
        { id: "t2", title: "Implement dark/light theme switching tokens", completed: true },
        { id: "t3", title: "Accessible high-frequency Figma token pipeline sync", completed: true },
        { id: "t4", title: "WCAG 2.2 AA Contrast audit & cross-team documentation", completed: false },
      ],
      status: "active",
      meetSyncTime: "Sprint Sync: Today, 3:00 PM",
      meetRoom: "Nexus Meet #room-design",
      meetUrl: "https://meet.google.com/new",
      createdAt: daysAgo(5),
      createdBy: "u-admin",
    },
    {
      id: "proj-seo-cluster",
      title: "Programmatic SEO Topic Cluster Pipeline",
      description: "High-yield permanent skill content structure with automated internal link graph validation.",
      version: "v1.2.0",
      leadId: "u-james",
      leadName: "James Carter",
      memberIds: ["u-james", "u-hana", "u-admin"],
      mentionedUsernames: ["james-carter", "hana-kim"],
      progress: 67,
      tasks: [
        { id: "t5", title: "Keyword entity clustering schema mapping", completed: true },
        { id: "t6", title: "Automated internal linking graph validation", completed: true },
        { id: "t7", title: "Publish pilot 20 evergreen topical hubs", completed: false },
      ],
      status: "active",
      meetSyncTime: "Weekly Review: Friday, 4:30 PM",
      meetRoom: "Growth Meet #cluster-review",
      meetUrl: "https://meet.google.com/new",
      createdAt: daysAgo(10),
      createdBy: "u-admin",
    },
    {
      id: "proj-crm-engine",
      title: "Omnichannel Lead Nurture & CRM Engine",
      description: "Automated multi-touch outreach architecture, high-intent lead scoring, and N8N pipeline integration with real-time conversion telemetry.",
      version: "v1.0.0",
      leadId: "u-ayaan",
      leadName: "Ayaan Malik",
      memberIds: ["u-ayaan", "u-priya", "u-admin"],
      mentionedUsernames: ["ayaan-malik", "priya-sharma"],
      progress: 100,
      tasks: [
        { id: "t8", title: "N8N Webhook payload normalization", completed: true },
        { id: "t9", title: "Lead scoring matrix configuration", completed: true },
        { id: "t10", title: "Multi-channel automated sequence deployment", completed: true },
      ],
      status: "completed",
      meetSyncTime: "Sprint Wrap-Up: Completed",
      meetRoom: "Archive Meet #crm-wrapup",
      meetUrl: "https://meet.google.com/new",
      createdAt: daysAgo(28),
      createdBy: "u-admin",
    },
  ];

  return {
    users,
    posts,
    comments,
    courses,
    progress,
    events,
    projects,
    messages,
    notifications,
    reviews,
    sales,
    sessions: [],
    communities,
  };
}
